LogPython: Error: `load_weights` requires h5py.
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 31, in <module>
LogPython: Error:   File "C:\Users\jh0228.STUDENT\Documents\TrumpDefense2020\TD2020\Content\Scripts\games\td2020\keras\NNet.py", line 148, in load_checkpoint
    self.nnet.model.load_weights(filepath)
LogPython: Error:   File "C:\Users\jh0228.STUDENT\Documents\TrumpDefense2020\TD2020\Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\tensorflow\python\keras\_impl\keras\engine\topology.py", line 1105, in load_weights
    raise ImportError('`load_weights` requires h5py.')
LogPython: Error: ImportError: `load_weights` requires h5py.


def load_checkpoint(self, folder='checkpoint', filename='checkpoint.pth.tar'):
	filepath = os.path.join(folder, filename)
	if not os.path.exists(filepath):
		raise ValueError("No model in path {}".format(filepath))

	print("NNet", "loading checkpoint", filepath)
	self.nnet.model.load_weights(filepath)






Package         Version
--------------- -------
absl-py         0.2.2  
numpy           1.14.5 
pandas          0.23.1 
pip             10.0.1 
protobuf        3.6.0  
pygame          1.9.3  
python-dateutil 2.7.3  
pytz            2018.4 
setuptools      39.2.0 
six             1.11.0 
tensorboard     1.6.0  
tensorflow-gpu  1.6.0  
termcolor       1.1.0  
Werkzeug        0.14.1 
wheel           0.31.1 


pip.install("h5py")

import h5py

output in python console:

DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jh0228.STUDENT\Documents\TrumpDefense2020\TD2020\Plugins\UnrealEnginePython\Binaries\Win64\Lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "h5py\_objects.pyx", line 1, in init h5py._objects
ImportError: DLL load failed: The specified procedure could not be found.


And after restarting computer and opening ue4 i get a crash, resulting in this output log:


[2018.06.28-17.39.05:649][118]LogWindows: Error: === Critical error: ===
[2018.06.28-17.39.05:650][118]LogWindows: Error: 
[2018.06.28-17.39.05:650][118]LogWindows: Error: Fatal error!
[2018.06.28-17.39.05:650][118]LogWindows: Error: 
[2018.06.28-17.39.05:650][118]LogWindows: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION 0x00000000
[2018.06.28-17.39.05:650][118]LogWindows: Error: 
[2018.06.28-17.39.05:650][118]LogWindows: Error: [Callstack] 0x0000000000000000 UnknownFunction []
[2018.06.28-17.39.05:650][118]LogWindows: Error: [Callstack] 0x000000006E4058EA _conv.cp36-win_amd64.pyd!UnknownFunction []
[2018.06.28-17.39.05:650][118]LogWindows: Error: [Callstack] 0x000000006E405859 _conv.cp36-win_amd64.pyd!UnknownFunction []
[2018.06.28-17.39.05:650][118]LogWindows: Error: [Callstack] 0x000000005D1DAF48 python36.dll!UnknownFunction []
[2018.06.28-17.39.05:651][118]LogWindows: Error: [Callstack] 0x000000005D1DA4F3 python36.dll!UnknownFunction []
[2018.06.28-17.39.05:651][118]LogWindows: Error: [Callstack] 0x000000005D1B8979 python36.dll!UnknownFunction []

but all packages are installed correctly:

pip.list()


Package         Version
--------------- -------
absl-py         0.2.2  
h5py            2.8.0  
numpy           1.14.5 
pandas          0.23.1 
pip             10.0.1 
protobuf        3.6.0  
pygame          1.9.3  
python-dateutil 2.7.3  
pytz            2018.4 
setuptools      39.2.0 
six             1.11.0 
tensorboard     1.6.0  
tensorflow-gpu  1.6.0  
termcolor       1.1.0  
Werkzeug        0.14.1 
wheel           0.31.1 